os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode7.3
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install openssl
      brew link --force openssl
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install libssl-dev
    fi
script:
  # Build SSL 
  - swift build
  - swift build --configuration release
  # Test SSL
  - swift test
notifications:
  email:
    on_success: never
    on_failure: change
  

